const CONSTANTS = {}
CONSTANTS.ENDPOINT = {}

CONSTANTS.HOME = '/'
CONSTANTS.LOGIN = '/login'
CONSTANTS.USERS = '/users'
CONSTANTS.PROJECTS = '/projects'
CONSTANTS.SETTINGS = '/settings'
CONSTANTS.PROFILE = '/profile'
CONSTANTS.CONTACT = 'contact'
CONSTANTS.PRIVACY = '/privacy'
CONSTANTS.ISALUTE = '/isalute'

CONSTANTS.ENDPOINT.LOGIN = '/api/login'
CONSTANTS.ENDPOINT.USERS = '/api/users'
CONSTANTS.ENDPOINT.PROJECTS = '/api/projects'
CONSTANTS.ENDPOINT.DOCUMENT = '/api/document'

export default CONSTANTS
